name: Test

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out project
        uses: actions/checkout@v4
      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2.0
        with:
          cmake-version: "3.23"
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"  # latest installed version
      - name: Set up development environment
        run: |
          make dev
      - name: Build project
        run: |
          make build
      - name: Run tests
        run: |
          make test
